export const Countries = [
    "Afghanistan",
    "Åland Islands",
     "Albania",
     "Algeria",
     "American Samoa",
     "AndorrA",
     "Angola",
     "Anguilla",
     "Antarctica",
     "Antigua and Barbuda",
     "Argentina", 
     "Armenia",
     "Aruba", 
     "Australia",
     "Austria", 
     "Azerbaijan",
     "Bahamas", 
     "Bahrain", 
     "Bangladesh",
     "Barbados",
     "Belarus",
     "Belgium",
     "Belize", 
     "Benin", 
     "Bermuda",
     "Bhutan",
     "Bolivia",
     "Bosnia and Herzegovina",
     "Botswana", 
     "Bouvet Island",
     "Brazil", 
     "British Indian Ocean Territory",
     "Brunei Darussalam", 
     "Bulgaria", 
     "Burkina Faso",
     "Burundi", 
     "Cambodia",
     "Cameroon",
     "Canada", 
     "Cape Verde",
     "Cayman Islands",
     "Central African Republic",
     "Chad", 
     "Chile",
     "China",
     "Colombia", 
     "Comoros",
     "Denmark", 
     "Egypt", 
     "Finland", 
     "Germany", 
     "Ghana", 
     "Gibraltar",
     "Greece",
     "Greenland",
     "Honduras",
     "India", 
     "Indonesia", 
     "Iran, Islamic Republic Of",
     "Iraq",
     "Italy", 
     "Japan", 
     "Jersey",
     "Korea, Republic of",
     "Kuwait",
     "Pakistan",
     "Palau", 
     "Qatar", 
     "Russian Federation",
     "RWANDA",
     "Singapore", 
     "South Africa",
     "Swaziland",
     "Sweden", 
     "Thailand", 
     "Trinidad and Tobago", 
     "United Arab Emirates",
     "United Arab Emirates",
     "United Kingdom",
     "United States",
     "Venezuela",
     "Viet Nam", 
     "Western Sahara",
     "Yemen", 
     "Zambia",
     "Zimbabwe"
    ]

    export const States = [
   "Andhra Pradesh",
   "Arunachal Pradesh",
   "Assam",
   "Bihar",
   "Chhattisgarh",
   "Chandigarh",
   "Dadra and Nagar Haveli",
   "Daman and Diu",
   "Delhi",
   "Goa",
   "Gujarat",
   "Haryana",
   "Himachal Pradesh",
   "Jammu and Kashmir",
   "Jharkhand",
   "Karnataka",
   "Kerala",
   "Madhya Pradesh",
   "Maharashtra",
   "Manipur",
   "Meghalaya",
   "Mizoram",
   "Nagaland",
   "Orissa",
   "Punjab",
   "Pondicherry",
   "Rajasthan",
   "Sikkim",
   "Tamil Nadu",
   "Tripura",
   "Uttar Pradesh",
   "Uttarakhand",
   "West Bengal"
    ]