export const GET_HOME_STORIES_REQUEST = 'GET_HOME_STORIES_REQUEST';
export const GET_HOME_STORIES_SUCCESS = 'GET_HOME_STORIES_SUCCESS';
export const GET_HOME_STORIES_FAILURE = 'GET_HOME_STORIES_FAILURE';
