export const READ_STORY_REQUEST = "READ_STORY_REQUEST";
export const READ_STORY_SUCCESS = "READ_STORY_SUCCESS";
export const READ_STORY_FAILURE = "READ_STORY_FAILURE";
export const UPVOTE_STORY_REQUEST = "UPVOTE_STORY_REQUEST";
export const UPVOTE_STORY_SUCCESS = "UPVOTE_STORY_SUCCESS";
export const UPVOTE_STORY_FAILURE = "UPVOTE_STORY_FAILURE";
